### PR TITLE
Fix segfault in zgesdd_

### LINKED ISSUE #324: Test suite segfaults when size paramater is increased to 100
```haskell
import Numeric.LinearAlgebra.Tests
main :: IO ()
main = runTests 100
```

```
------ svd
+++ OK, passed 100 tests.
Segmentation fault: 11
```

This is on MacOS. It seems to happen only on complex numbers, and I'm pretty sure that it's the work size passed to `zgesdd_`.

### PR DESCRIPTION
**Pull request by HuwCampbell**
Fixes #324.

I changed the variable name `q` to `mn` to match the documentation in the [source](http://www.netlib.org/lapack/explore-html/d8/d54/zgesdd_8f_source.html); changed the broken line to not assume a recent lapack version and turned it back on; and made the more pessimistic call not assuming `mx >> mn` (how is that computable anyway?).

This fixes the test suite for me on OSX with larger sized matrices (tested 100, which would reliably segfault for me). It would be good if someone could do some tests on Linux with increased sizes as well.

### CODE REVIEW

File: packages/base/src/Internal/C/lapack-aux.c [hunk 1]
```diff
@@ -281,49 +307,68 @@ int zgesdd_ (char *jobz, integer *m, integer *n,
...
+            ldvt = mn;
         }
     }
     DEBUGMSG("svd_l_Cdd");
-    integer* iwk = (integer*) malloc(8*q*sizeof(integer));
-    CHECK(!iwk,MEM);
+    integer* iwk = (integer*) malloc(8*mn*sizeof(integer));
+    UNWIND(!iwk,MEM,cleanup0);
+
+    // Docs: http://www.netlib.org/lapack/explore-html/d8/d54/zgesdd_8f_source.html
```
Comment (HuwCampbell) [inline packages/base/src/Internal/C/lapack-aux.c:334]: This is the pertinent section

**Comment by idontgetoutmuch** [comment]
> Fixes #324.
> 
> I changed the variable name `q` to `mn` to match the documentation in the [source](http://www.netlib.org/lapack/explore-html/d8/d54/zgesdd_8f_source.html); changed the broken line to not assume a recent lapack version and turned it back on; and made the more pessimistic call not assuming `mx >> mn` (how is that computable anyway?).
> 
> This fixes the test suite for me on OSX with larger sized matrices (tested 100, which would reliably segfault for me). It would be good if someone could do some tests on Linux with increased sizes as well.

The tests pass on CI which is ubuntu.
